---
# tasks file for vnfm

- include_vars: images.yml

- name: Downloading Image from HTTP Server
  get_url:
    url: "{{ item.value.url }}"
    dest: "{{ resources }}/{{ item.value.file }}"
  with_dict: "{{ images }}"

- name: Uploading Image to Glance
  os_image:
    auth: "{{ auth }}"
    name: "{{ item.value.name }}"
    filename: "{{ resources }}/{{ item.value.file }}"
    disk_format: qcow2
    container_format: bare
    state: present
  with_dict: "{{ images }}"
